- name: Install Dummy Splunk Certificate
  hosts: splunk_servers
  become: true
  vars:
    cert_source_path: /root/2025/dummy_cert.pem
    cert_dest_path: /root/2025/splunk-install/splunk_cert_install/etc/auth/certs/dummy_cert.pem
    cert_backup_path: /root/2025/splunk-install/splunk_cert_install/etc/auth/certs/dummy_cert.pem.bak

  tasks:

    - name: Ensure certs directory exists
      file:
        path: /root/2025/splunk-install/splunk_cert_install/etc/auth/certs
        state: directory
        mode: '0755'

    - name: Check if dummy certificate exists
      stat:
        path: "{{ cert_dest_path }}"
      register: cert_stat

    - name: Backup existing certificate if it exists
      copy:
        src: "{{ cert_dest_path }}"
        dest: "{{ cert_backup_path }}"
        remote_src: yes
      when: cert_stat.stat.exists


    - name: Copy new certificate to Splunk certs folder
      copy:
        src: "{{ cert_source_path }}"
        dest: "{{ cert_dest_path }}"
        owner: madhuchilipi
        group: madhuchilipi
        mode: '0644'